name: job deploy server
 
on:
  push:
    branches:
      - 'deloy_server_v1'

jobs:
  build_marketplace:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./BE
          file: ./BE/Dockerfile
          push: true
          tags: vinhnv06/server_shose:shose_version_1
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./FE
          file: ./FE/Dockerfile
          push: true
          tags: vinhnv06/client_shose:shose_version_fe_1

      - 
       name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v1.0.0
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.PORT }}
         script: |
            cd vinhnv_shose
            docker pull vinhnv06/server_shose:shose_version_1
            docker pull vinhnv06/client_shose:shose_version_fe_1
            docker-compose up -d --build springboot-container
            docker-compose up -d --build react-container
            docker image prune
